### PR TITLE
RemoteFuncAsync for generic async support (Func<Task>) + migration

### PR DESCRIPTION
**Pull request by raphsharp**
Hello, I added a generic Func<Task> support (the RemoteFuncAsync class).
I also have migrated the Units test from the inactive MSTest to the open source XUnit in last version. (I have had strange issues with RemoteFuncAsync unit tests : a ThreadAbortException was thrown in release mode only with the 4 & 5 param methods, and nothing in debug mode, and nothing when using it in a test project in release).

### CODE REVIEW

**Comment by jduv** [comment]
Very slick. Pull accepted.

**Comment by jduv** [comment]
Some of the code added doesn't follow the style in the toolkit. I'll clean those classes up before I do a new package--expect possible breaking changes.

**Comment by petersondrew** [comment]
This is causing me issues because the AppDomainContext is now changing the ApplicationBase directory out from under me, regardless of what I pass in my setup info https://github.com/raphsharp/AppDomainToolkit/commit/9d56d8870a38672e15b829b0c531dc2b4ced9597#diff-f92b4bb08c94b178a6bacc1bba61f5afR95
Perhaps this is a fix for using Xunit now, but it's breaking my code. @raphsharp Any ideas?

**Comment by jduv** [comment]
All, I'll probably back this out. Sorry for all the late replies--the day job has me swamped. 

Sent from jduv's iPhone 
(706-781-5146)

**Comment by petersondrew** [comment]
You responded within 2 minutes - I'd say that's pretty quick response time :smile: 
Thanks - I would take a crack at fixing it but I'm also swamped. Must be that time of year.

**Comment by raphsharp** [comment]
Hi, sorry for the late answer, I forgot I've added 3 lines of a quick and
dirty fix for xunit. I'll try to look at this week, I believe it's related
to the way xunit run it's own AppContext.

**Comment by JoeBrockhaus** [comment]
I've been meaning to take a look at this set of changes as well as similar out of band changes I've made, but am also swamped. 

My changes were to support conditional overrides of the search paths, in addition to extensions to RemoteFunc to be more flexible. 

I'll make time this week - hopefully even tonight - to take a gander.

Sent from Windows Phone 8.1 Dev Preview

-----Original Message-----

**Comment by jduv** [comment]
Backed it out for now--let's work on making this a cleaner pull next time :). I'll spend more time with it next go around.

**Comment by raphsharp** [comment]
The problem is XUnit creates it's own AppDomain with ShadowCopy enabled, and the .Net Framework dispatch each DLL in separate folders. Something like : 
C:\Users\UserXXX\AppData\Local\Temp\478c6992-0818-4353-b380-0387fc88916a\478c6992-0818-4353-b380-0387fc88916a\assembly\dl3\7d98d203\8021e20b_a65cd001

In AppDomainContext's Create method, the root assembly path is extracted from Assembly.GetExecutingAssembly().Location. And in this path there's only one DLL. I think the problem we have here is not specific to XUnit, but general to all AppDomainToolkit usages inside custom AppDomains.

Maybe one clean way to go is, in AppDomainContext's Create() method, to extract the root path from AppDomain.CurrentDomain.SetupInformation.CachePath instead of Assembly.GetExecutingAssembly().Location. The CachePath property contains the shared root of all DLL ("C:\\Users\\UserXXX\\AppData\\Local\\Temp\\eb3d1cfa-4c7c-4405-b2ad-dcab2778df6d"). In this case, we have to also modify PathBasedAssemblyResolver to resolve recursively the missing DLLs from the code base path.

One other way to go could be to disable XUnit's shadow copy. But it doesn't solve the more general problem of resolving DLL in case of calls to AppDomainToolkit from a custom AppDomain. I know it's possible to disable XUnit's shadow copy in MSBuild task, but I don't find a way to do it in a clean way in visual studio test runner.

**Comment by raphsharp** [comment]
Okay, I found the trick. In AppDomainContext.Create() method, the problem comes from the line :
string rootDir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);

If we replace it with the following 
string rootDir = Path.GetDirectoryName(new Uri(Assembly.GetExecutingAssembly().CodeBase).LocalPath);

then everything works nicely.
I will create a new pull request with this fix.

**Pull request merged**
