### PR TITLE
Adds Async support + XUnit + Fix AppDomainSetup root path in case of AppDomain inception

### PR DESCRIPTION
**Pull request by raphsharp**
- Adds generic support for awaitable Func<Task>
- Migrates tests from MSTest to Xunit
- Fix the AppDomainSetup path in AppDomainContext.Create() method. (use Assembly.GetExecutingAssembly().CodeBase instead of Assembly.GetExecutingAssembly().Location.) which produces errors when creating an AppDomain from another newly created AppDomain (aka AppDomain inception)

### CODE REVIEW

**Comment by jduv** [comment]
It's frustrating to me that no one has invented a standard for Assert.* APIs. Having to rename every method call is ridiculous (albeit fast with SublimeText). Thank you sir, good work.

**Comment by raphsharp** [comment]
Perhaps @petersondrew should try to test if this fix doesn't cause issues in his case ? (https://github.com/jduv/AppDomainToolkit/pull/13#issuecomment-77894257)
I think it could be a good idea to create an unit test for his specific case.

**Comment by petersondrew** [comment]
I'll take a look if a get a few minutes - though there's nothing special about my case. I'm simply instantiating an AppDomainContext using an AppDomainSetup object that has the ApplicationBase property set. The bug in your original PR was that you were changing the ApplicationBase in the constructor, which overwrote what I had passed in my AppDomainSetup object.

**Comment by JoeBrockhaus** [comment]
The issue I had, which required me to change a lot, is that depending on the circumstances of the assembly I'm loading (and where its dependencies are), I would need to craft all of the setup and path information differently. 

It also would depend on what context the code was being run in, similar to the issues you're having with unit tests. 

My case may have been more finicky because my dependencies were version-specific, so I wouldn't want to always load an assembly in the calling AppDomain's ApplicationBase, because it might not be the correct version of the dependency.

I still haven't looked back at this yet, I hope to be able to help 😆 

Sent from Windows Phone 8.1 Dev Preview

-----Original Message-----

**Comment by raphsharp** [comment]
@jduv : Is it possible to update the nuget package ?

**Comment by jduv** [comment]
Sure, still reviewing. 

Sent from jduv's iPhone 
(706-781-5146)

**Pull request merged**
